### ISSUE TITLE
Провести проверку на большом файле

### ISSUE THREAD

**Issue by alexkoss** [Papatopit/UniqueValues#1]
Файл: https://github.com/PeacockTeam/new-job/releases/download/v1.0/lng-big.7z

В ответе должно быть количество групп и время выполнения.

**Comment by alexkoss** [comment]
Буду ждать до понедельника, потом потеряет актуальность.

**Comment by Papatopit** [comment]
20762 групп
48 сек

**Comment by alexkoss** [comment]
Ответ неправильный, не укладывается в ТЗ по скорости. Попробуете ещё раз?

**Comment by Papatopit** [comment]
да, конечно попробую!
